[build]
  command = "next build"
  publish = ".next"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["mongodb", "mongoose"]
  included_files = ["utils/**", "libs/**", "models/**"]

[functions."tips-background"]
  schedule = "40 23 * * *"

[functions."reset-background"]
  schedule = "1 5 * * *"

[functions."test-background"]
  schedule = "35 5 * * *"

[[plugins]]
  package = "@netlify/plugin-nextjs"