[build]
  command = "next build"
  publish = ".next"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["mongodb", "mongoose"]
  included_files = ["utils/**", "libs/**", "models/**"]

[functions."test-background"]
  schedule = "35 5 * * *"

[functions."scheduledTips-background"]
  schedule = "40 23 * * *" # Runs at 6:40 PM EST daily
  queryParams = { code = "test", tipTime = "7pm" }

[functions."scheduledTest-background"]
  schedule = "27 5 * * *" # Runs at 12:10 AM EST daily
  queryParams = { code = "test", tipTime = "7pm" }

[[plugins]]
  package = "@netlify/plugin-nextjs"