[build]
  command = "next build"
  publish = ".next"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = [
    "mongodb", 
    "mongoose", 
    "express", 
    "serverless-http", 
    "@farcaster/miniapp-node", 
    "axios"
  ]
  included_files = [
    "utils/**", 
    "libs/**", 
    "models/**", 
    "node_modules/sharp/**/*"
  ]

[[redirects]]
  from = "/api/webhook"
  to = "/.netlify/functions/webhook"
  status = 200
  force = true

[functions."reset-background"]
  schedule = "1 5 * * *"

[functions."test-background"]
  schedule = "35 5 * * *"

[functions."score-background"]
  schedule = "57 4 * * *"

[functions."raffle-background"]
  schedule = "40 4 * * *"

[functions."rewards-background"]
  schedule = "30 4 * * *"

[functions."autofund-betr-background"]
  schedule = "35 13 * * 2"

[[plugins]]
  package = "@netlify/plugin-nextjs"
