[build]
  command = "next build"
  publish = ".next"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["mongodb", "mongoose"]
  included_files = ["utils/**", "libs/**", "models/**"]
  timeout = "900"

[functions.scheduledTips]
  schedule = "40 22 * * *" # Runs at 6:40 PM EST daily
  path = "scheduledTips"
  queryParams = { code = "test", tipTime = "7pm" }

[[plugins]]
  package = "@netlify/plugin-nextjs"