[build]
  command = "next build"
  publish = ".next"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["mongodb", "mongoose", "sharp"]
  included_files = ["utils/**", "libs/**", "models/**", "node_modules/sharp/**/*"]

[functions."tips-background"]
  schedule = "40 22 * * *"

[functions."reset-background"]
  schedule = "1 5 * * *"

[functions."test-background"]
  schedule = "35 5 * * *"

[functions."raffle-background"]
  schedule = "1 4 * * *"

[[plugins]]
  package = "@netlify/plugin-nextjs"